config/routes.rb
Rails.application.routes.draw do
  root :to => 'jobs#index'
  resources :jobs
  resources :magics
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => true, :uniqueness => true

  has_many :magics, :through => :job_magics
  has_many :job_magics, :dependent => :destroy

  accepts_nested_attributes_for :job_magics, :allow_destroy => true,
    :reject_if => lambda{ |attrs| attrs[:magic_id].blank? }
end

app/models/job_magic.rb
class JobMagic < ActiveRecord::Base
  belongs_to :job
  belongs_to :magic
end

app/models/magic.rb
class Magic < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many :jobs, :through => :job_magics
  has_many :job_magics, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find params[:id]
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find params[:id]
  end

  def create
    @job = Job.new params[:job]
    if @job.save
      redirect_to @job, :notice => 'Job was successfully created.'
    else
      render :action => 'new', :error => @job.errors.full_messages
    end
  end

  def update
    @job = Job.find params[:id]
    if @job.update_attributes params[:job]
      redirect_to @job, :notice => 'Job was successfully updated.'
    else
      render :action => 'edit', :error => @job.errors.full_messages
    end
  end

  def destroy
    @job = Job.find params[:id]
    @job.destroy
    redirect_to jobs_url
  end
end

app/controllers/magics_controller.rb
class MagicsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/magics_helper.rb
module MagicsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Job</legend>
    <dl>
      <dt><label for="job_title">Title:</label></dt>
      <dd><%= f.text_field :title %></dd>
    </dl>
    <dl>
      <dt><label>Magics:</label></dt>
      <dd>
        <ul id="job_magics">
          <%= f.fields_for :job_magics do |job_magic| -%>
            <%= render 'job_magic_fields', :f => job_magic %>
          <%- end -%>
        </ul>
        <p><%= link_to_add_fields 'Add Magic', f, :job_magics, '#job_magics' %></p>
      </dd>
    </dl>
    <%= f.submit %> or <%= link_to 'Cancel', jobs_path %>
  </fieldset>
<%- end -%>

app/views/jobs/_job_magic_fields.html.erb
<li class="fields">
  <%= f.hidden_field :id %>
  <%= f.select :magic_id, options_for_select([['---', nil]] + Magic.all.map{|m| [m.name, m.id]}, f.object.magic_id) %>
  <%= link_to_remove_fields 'Remove Magic', f %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestNestedFormApps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>